### ISSUE TITLE
Double Event Count And Issues With Outbound Tracking

### ISSUE THREAD

**Issue by coleh33** [googleanalytics/autotrack#158] opened 2017-03-21 17:54 UTC
I am having some issues implementing the outbound link tracking.  The code below is triggering two events inside Google Analytics but it's two events for the attributes listed below and no outbound link tracking event is firing.

`<a class="article-sharing-icon" href="<?php echo $facebookURL; ?>" target="_blank" ga-on="click" ga-event-category="Share Icon" ga-event-action="click" ga-event-label="Facebook">
  Facebook Share
</a>`

Should outbound link tracking be working with elements that are event tracking as well or will they conflict?  I have tested the outbound link tracking on just a normal URL inside page content and it works just fine.  It appears to only be an issue with items that already are tracking events and is firing two events for those items and those events are the same for the attributes above.

**Comment by WillsB3** [comment] 2017-03-21 22:39
I'm also seeing events being sent twice for every click on a link annotated with the event tracking attributes.

**Comment by philipwalton** [comment] 2017-03-23 18:13
By default, if you have the `eventTracker` and `outboundLinkTracker` plugins required and you have event tracking attributes on an outbound link, you'll get both events.

If you don't want this behavior, you can customize the logic in the [`linkSelector`](https://github.com/googleanalytics/autotrack/blob/master/docs/plugins/outbound-link-tracker.md#options) option to exclude links with a `ga-on` attribute like so:

```js
ga('require', 'outboundLinkTracker', {
  linkSelector: 'a:not([ga-on])',
});
```

**Comment by WillsB3** [comment] 2017-03-23 20:33
That works for me - thanks!

**Comment by philipwalton** [comment] 2017-06-02 20:21
I'm going to close this as I think everything is working as intended. Feel free to comment if there's still something to do here.

**Closed by philipwalton** 2017-06-02 20:21 UTC
