### ISSUE TITLE
Target _blank will cause serious failures

### ISSUE THREAD

**Issue by yamlfd** [googleanalytics/autotrack#62] opened 2016-04-30 09:00 UTC
I have reviewed your code because of https://www.drupal.org/node/2671716 and found some issues with the code.

This open _blank causes serious malfunctions.
```
if (!navigator.sendBeacon) {
      link.target = '_blank';
    }
```

The following issues and amyn other will arise:

- https://www.drupal.org/node/1057914

**Comment by philipwalton** [comment] 2016-04-30 20:00
I'm not sure the issues raised in this thread apply here. As far as I can tell, the problem described is specific to links with an inline `onclick` handler. Is that the case?

If so, a particular site could use the `shouldTrackOutboundLink` config option to customize the logic.

**Comment by yamlfd** [comment] 2016-04-30 20:49
Can you describe what xou mean with an inline onclick handler?

I see the plugin bind an event to all A tags. This means you have 10.000 event bindings on a page that has 10.000 links. And than this issue occur.

**Comment by philipwalton** [comment] 2016-04-30 21:05
An inline click handler is one that's inserted directly into the HTML source. For example:

```html
<a onclick="alert('hello')">...</a>
```

In the thread you linked to, the bug reporter describes the following inline event handler `target="onclick = "window.open (this.href); return false;"` (which I think actually is a typo because that's not valid HTML, so it's hard to say for sure what the problem is in that bug).

**Comment by philipwalton** [comment] 2016-04-30 21:17
Also, you said in your email (but it looks like you edited it from your comment):

> I see the plugin bind an event to all A tags. This means you have 10.000 event bindings on a page that has 10.000 links. And than this issue occur.

Just in case there's any confusion, this is not the case. Autotrack only binds a single event handler to the `document` to listen for link clicks, no matter how many links are on the page.

Here's the code where that happens as of version 0.6.5:
https://github.com/googleanalytics/autotrack/blob/0.6.5/lib/plugins/outbound-link-tracker.js#L40-L41

**Comment by philipwalton** [comment] 2016-07-19 22:37
Closing due to lack of sufficient explanation of what failures occur due to this. Feel free to reopen if you have more information.

**Closed by philipwalton** 2016-07-19 22:37 UTC

**Comment by yamlfd** [comment] 2016-09-17 20:31
If you have a link with `onclick = "window.open (this.href); return false;` or a map or a js callback that catches your clicks it may have some js code attached that preventDefault browser behaviour. But if you add a target this is causing a new tab to open just because you embedde some external code. I had 4/5 different bugs about this when I tries to add target blank.

**Comment by philipwalton** [comment] 2016-09-18 04:26
I'm not following what you're saying. Can you post a reduced test case that demonstrates the issue?
